(function(g){var window=this;'use strict';var vWa=function(a,b){a.Oa("onAutonavCoundownStarted",b)},l3=function(a,b,c){g.O(a.element,"ytp-suggestion-set",!!b.videoId);
var d=b.playlistId;c=b.zf(c?c:"mqdefault.jpg");var e=null,f=null;b instanceof g.tD&&(b.lengthText?(e=b.lengthText||null,f=b.Rr||null):b.lengthSeconds&&(e=g.XH(b.lengthSeconds),f=g.XH(b.lengthSeconds,!0)));var k=!!d;d=k&&"RD"===g.pD(d).type;var l=b instanceof g.tD?b.isLivePlayback:null,m=b instanceof g.tD?b.isUpcoming:null;c={title:b.title,author:b.author,author_and_views:b.shortViewCount?b.author+" \u2022 "+b.shortViewCount:b.author,aria_label:b.ariaLabel||g.KF("Watch $TITLE",{TITLE:b.title}),duration:e,
timestamp:f,url:b.Zl(),is_live:l,is_upcoming:m,is_list:k,is_mix:d,background:c?"background-image: url("+c+")":"",views_and_publish_time:b.shortViewCount?b.shortViewCount+" \u2022 "+b.publishedTimeText:b.publishedTimeText,autoplayAlternativeHeader:b.Oo};b instanceof g.sD&&(c.playlist_length=b.playlistLength);a.update(c)},m3=function(a){var b=a.V(),c=b.j;
g.V.call(this,{G:"a",L:"ytp-autonav-suggestion-card",W:{href:"{{url}}",target:c?b.K:"","aria-label":"{{aria_label}}","data-is-live":"{{is_live}}","data-is-list":"{{is_list}}","data-is-mix":"{{is_mix}}","data-is-upcoming":"{{is_upcoming}}"},U:[{G:"div",Ea:["ytp-autonav-endscreen-upnext-thumbnail","ytp-autonav-thumbnail-small"],W:{style:"{{background}}"},U:[{G:"div",W:{"aria-label":"{{timestamp}}"},Ea:["ytp-autonav-timestamp"],oa:"{{duration}}"},{G:"div",Ea:["ytp-autonav-live-stamp"],oa:"Live"},{G:"div",
Ea:["ytp-autonav-upcoming-stamp"],oa:"Upcoming"},{G:"div",L:"ytp-autonav-list-overlay",U:[{G:"div",L:"ytp-autonav-mix-text",oa:"Mix"},{G:"div",L:"ytp-autonav-mix-icon"}]}]},{G:"div",Ea:["ytp-autonav-endscreen-upnext-title","ytp-autonav-title-card"],oa:"{{title}}"},{G:"div",Ea:["ytp-autonav-endscreen-upnext-author","ytp-autonav-author-card"],oa:"{{author}}"},{G:"div",Ea:["ytp-autonav-endscreen-upnext-author","ytp-autonav-view-and-date-card"],oa:"{{views_and_publish_time}}"}]});this.I=a;this.suggestion=
null;this.j=c;this.Ma("click",this.onClick);this.Ma("keypress",this.onKeyPress)},o3=function(a,b){b=void 0===b?!1:b;
g.V.call(this,{G:"div",L:"ytp-autonav-endscreen-countdown-container"});var c=this;this.J=b;this.D=void 0;this.u=0;b=a.V();var d=b.j;this.I=a;this.suggestion=null;this.onVideoDataChange("newdata",this.I.getVideoData());this.T(a,"videodatachange",this.onVideoDataChange);this.j=new g.V({G:"div",L:"ytp-autonav-endscreen-upnext-container",W:{"aria-label":"{{aria_label}}","data-is-live":"{{is_live}}","data-is-list":"{{is_list}}","data-is-mix":"{{is_mix}}","data-is-upcoming":"{{is_upcoming}}"},U:[{G:"div",
L:"ytp-autonav-endscreen-upnext-header"},{G:"div",L:"ytp-autonav-endscreen-upnext-alternative-header",oa:"{{autoplayAlternativeHeader}}"},{G:"a",L:"ytp-autonav-endscreen-link-container",W:{href:"{{url}}",target:d?b.K:""},U:[{G:"div",L:"ytp-autonav-endscreen-upnext-thumbnail",W:{style:"{{background}}"},U:[{G:"div",W:{"aria-label":"{{timestamp}}"},Ea:["ytp-autonav-timestamp"],oa:"{{duration}}"},{G:"div",Ea:["ytp-autonav-live-stamp"],oa:"Live"},{G:"div",Ea:["ytp-autonav-upcoming-stamp"],oa:"Upcoming"}]},
{G:"div",L:"ytp-autonav-endscreen-video-info",U:[{G:"div",L:"ytp-autonav-endscreen-premium-badge"},{G:"div",L:"ytp-autonav-endscreen-upnext-title",oa:"{{title}}"},{G:"div",L:"ytp-autonav-endscreen-upnext-author",oa:"{{author}}"},{G:"div",L:"ytp-autonav-view-and-date",oa:"{{views_and_publish_time}}"},{G:"div",L:"ytp-autonav-author-and-view",oa:"{{author_and_views}}"}]}]}]});g.H(this,this.j);this.j.Ba(this.element);d||this.T(this.j.Ca("ytp-autonav-endscreen-link-container"),"click",this.ZK);this.I.Ab(this.element,
this,115127);this.I.Ab(this.j.Ca("ytp-autonav-endscreen-link-container"),this,115128);this.overlay=new g.V({G:"div",L:"ytp-autonav-overlay"});g.H(this,this.overlay);this.overlay.Ba(this.element);this.B=new g.V({G:"div",L:"ytp-autonav-endscreen-button-container"});g.H(this,this.B);this.B.Ba(this.element);this.cancelButton=new g.V({G:"button",Ea:["ytp-autonav-endscreen-upnext-button","ytp-autonav-endscreen-upnext-cancel-button"],W:{"aria-label":"Cancel autoplay"},oa:"Cancel"});g.H(this,this.cancelButton);
this.cancelButton.Ba(this.B.element);this.cancelButton.Ma("click",this.UT,this);this.I.Ab(this.cancelButton.element,this,115129);this.playButton=new g.V({G:"a",Ea:["ytp-autonav-endscreen-upnext-button","ytp-autonav-endscreen-upnext-play-button"],W:{href:"{{url}}",role:"button","aria-label":"Play next video"},oa:"Play Now"});g.H(this,this.playButton);this.playButton.Ba(this.B.element);this.playButton.Ma("click",this.ZK,this);this.I.Ab(this.playButton.element,this,115130);this.C=new g.L(function(){n3(c)},
500);
g.H(this,this.C);this.YK();this.T(a,"autonavvisibility",this.YK)},r3=function(a){var b=a.I.Ek(!0,a.I.isFullscreen());
g.O(a.element,"ytp-autonav-endscreen-small-mode",a.gg(b));g.O(a.element,"ytp-autonav-endscreen-is-premium",!!a.suggestion&&!!a.suggestion.jD);g.O(a.I.getRootNode(),"ytp-autonav-endscreen-cancelled-state",!a.I.We());g.O(a.I.getRootNode(),"countdown-running",a.Qi());g.O(a.element,"ytp-player-content",a.I.We());g.Km(a.overlay.element,{width:b.width+"px"});if(!a.Qi()){a.I.We()?p3(a,Math.round(q3(a)/1E3)):p3(a);b=!!a.suggestion&&!!a.suggestion.Oo;var c=a.I.We()||!b;g.O(a.element,"ytp-autonav-endscreen-upnext-alternative-header-only",
!c&&b);g.O(a.element,"ytp-autonav-endscreen-upnext-no-alternative-header",c&&!b);g.YG(a.B,a.I.We())}},n3=function(a){var b=q3(a),c=Math,d=c.min;
var e=a.u?Date.now()-a.u:0;c=d.call(c,e,b);p3(a,Math.ceil((b-c)/1E3));500>=b-c&&a.Qi()?a.select(!0):a.Qi()&&a.C.start()},q3=function(a){var b=a.I.qr();
return 0<=b?b:g.sB(a.I.V().experiments,"autoplay_time")||1E4},p3=function(a,b){b=void 0===b?-1:b;
a=a.j.Ca("ytp-autonav-endscreen-upnext-header");g.ei(a);if(0<=b){b=String(b);var c="Up next in $SECONDS".match(RegExp("\\$SECONDS","gi"))[0],d="Up next in $SECONDS".indexOf(c);if(0<=d){a.appendChild(g.di("Up next in $SECONDS".slice(0,d)));var e=g.ci("span");g.Ep(e,"ytp-autonav-endscreen-upnext-header-countdown-number");g.ji(e,b);a.appendChild(e);a.appendChild(g.di("Up next in $SECONDS".slice(d+c.length)));return}}g.ji(a,"Up next")},s3=function(a,b){g.V.call(this,{G:"div",
Ea:["html5-endscreen","ytp-player-content",b||"base-endscreen"]});this.created=!1;this.player=a},t3=function(a){g.V.call(this,{G:"div",
Ea:["ytp-upnext","ytp-player-content"],W:{"aria-label":"{{aria_label}}"},U:[{G:"div",L:"ytp-cued-thumbnail-overlay-image",W:{style:"{{background}}"}},{G:"span",L:"ytp-upnext-top",U:[{G:"span",L:"ytp-upnext-header",oa:"Up Next"},{G:"span",L:"ytp-upnext-title",oa:"{{title}}"},{G:"span",L:"ytp-upnext-author",oa:"{{author}}"}]},{G:"a",L:"ytp-upnext-autoplay-icon",W:{role:"button",href:"{{url}}","aria-label":"Play next video"},U:[{G:"svg",W:{height:"100%",version:"1.1",viewBox:"0 0 72 72",width:"100%"},
U:[{G:"circle",L:"ytp-svg-autoplay-circle",W:{cx:"36",cy:"36",fill:"#fff","fill-opacity":"0.3",r:"31.5"}},{G:"circle",L:"ytp-svg-autoplay-ring",W:{cx:"-36",cy:"36","fill-opacity":"0",r:"33.5",stroke:"#FFFFFF","stroke-dasharray":"211","stroke-dashoffset":"-211","stroke-width":"4",transform:"rotate(-90)"}},{G:"path",L:"ytp-svg-fill",W:{d:"M 24,48 41,36 24,24 V 48 z M 44,24 v 24 h 4 V 24 h -4 z"}}]}]},{G:"span",L:"ytp-upnext-bottom",U:[{G:"span",L:"ytp-upnext-cancel"},{G:"span",L:"ytp-upnext-paused",
oa:"Autoplay is paused"}]}]});this.api=a;this.cancelButton=null;this.D=this.Ca("ytp-svg-autoplay-ring");this.B=this.notification=this.j=this.suggestion=null;this.C=new g.L(this.OA,5E3,this);this.u=0;var b=this.Ca("ytp-upnext-cancel");this.cancelButton=new g.V({G:"button",Ea:["ytp-upnext-cancel-button","ytp-button"],W:{tabindex:"0","aria-label":"Cancel autoplay"},oa:"Cancel"});g.H(this,this.cancelButton);this.cancelButton.Ma("click",this.VT,this);this.cancelButton.Ba(b);this.cancelButton&&this.api.Ab(this.cancelButton.element,
this,115129);g.H(this,this.C);this.api.Ab(this.element,this,18788);b=this.Ca("ytp-upnext-autoplay-icon");this.T(b,"click",this.XT);this.api.Ab(b,this,115130);this.aL();this.T(a,"autonavvisibility",this.aL);this.T(a,"mdxnowautoplaying",this.EY);this.T(a,"mdxautoplaycanceled",this.FY);g.O(this.element,"ytp-upnext-mobile",this.api.V().isMobile)},wWa=function(a,b){return b?b:0<=a.api.qr()?a.api.qr():g.sB(a.api.V().experiments,"autoplay_time")||1E4},u3=function(a,b){b=wWa(a,b);
var c=Math,d=c.min;var e=(0,g.R)()-a.u;c=d.call(c,e,b);b=0===b?1:Math.min(c/b,1);a.D.setAttribute("stroke-dashoffset",""+-211*(b+1));1<=b&&a.Qi()&&3!==a.api.getPresentingPlayerType()?a.select(!0):a.Qi()&&a.j.start()},v3=function(a){s3.call(this,a,"autonav-endscreen");
this.overlay=this.videoData=null;this.table=new g.V({G:"div",L:"ytp-suggestion-panel",U:[{G:"div",Ea:["ytp-autonav-endscreen-upnext-header","ytp-autonav-endscreen-more-videos"],oa:"More videos"}]});this.K=new g.V({G:"div",L:"ytp-suggestions-container"});this.videos=[];this.B=null;this.D=this.J=!1;this.u=new o3(this.player);g.H(this,this.u);this.u.Ba(this.element);a.getVideoData().ud?this.j=this.u:(this.j=new t3(a),g.EJ(this.player,this.j.element,4),g.H(this,this.j));this.overlay=new g.V({G:"div",
L:"ytp-autonav-overlay-cancelled-state"});g.H(this,this.overlay);this.overlay.Ba(this.element);this.C=new g.iA(this);g.H(this,this.C);g.H(this,this.table);this.table.Ba(this.element);this.table.show();g.H(this,this.K);this.K.Ba(this.table.element);this.hide()},w3=function(a){var b=a.We();
b!==a.D&&(a.D=b,a.player.ea("autonavvisibility"),a.D?(a.u!==a.j&&a.u.hide(),a.table.hide()):(a.u!==a.j&&a.u.show(),a.table.show()))},x3=function(a){s3.call(this,a,"subscribecard-endscreen");
this.j=new g.V({G:"div",L:"ytp-subscribe-card",U:[{G:"img",L:"ytp-author-image",W:{src:"{{profilePicture}}"}},{G:"div",L:"ytp-subscribe-card-right",U:[{G:"div",L:"ytp-author-name",oa:"{{author}}"},{G:"div",L:"html5-subscribe-button-container"}]}]});g.H(this,this.j);this.j.Ba(this.element);var b=a.getVideoData();this.subscribeButton=new g.hL("Subscribe",null,"Unsubscribe",null,!0,!1,b.Zj,b.subscribed,"trailer-endscreen",null,null,a);g.H(this,this.subscribeButton);this.subscribeButton.Ba(this.j.Ca("html5-subscribe-button-container"));
this.T(a,"videodatachange",this.Ha);this.Ha();this.hide()},y3=function(a){var b=a.V(),c=g.mA||g.pC?{style:"will-change: opacity"}:void 0,d=b.j,e=["ytp-videowall-still"];
b.isMobile&&e.push("ytp-videowall-show-text");g.V.call(this,{G:"a",Ea:e,W:{href:"{{url}}",target:d?b.K:"","aria-label":"{{aria_label}}","data-is-live":"{{is_live}}","data-is-list":"{{is_list}}","data-is-mix":"{{is_mix}}"},U:[{G:"div",L:"ytp-videowall-still-image",W:{style:"{{background}}"}},{G:"span",L:"ytp-videowall-still-info",U:[{G:"span",L:"ytp-videowall-still-info-bg",U:[{G:"span",L:"ytp-videowall-still-info-content",W:c,U:[{G:"span",L:"ytp-videowall-still-info-title",oa:"{{title}}"},{G:"span",
L:"ytp-videowall-still-info-author",oa:"{{author_and_views}}"},{G:"span",L:"ytp-videowall-still-info-live",oa:"Live"},{G:"span",L:"ytp-videowall-still-info-duration",oa:"{{duration}}"}]}]}]},{G:"span",Ea:["ytp-videowall-still-listlabel-regular","ytp-videowall-still-listlabel"],U:[{G:"span",L:"ytp-videowall-still-listlabel-icon"},"Playlist",{G:"span",L:"ytp-videowall-still-listlabel-length",U:[" (",{G:"span",oa:"{{playlist_length}}"},")"]}]},{G:"span",Ea:["ytp-videowall-still-listlabel-mix","ytp-videowall-still-listlabel"],
U:[{G:"span",L:"ytp-videowall-still-listlabel-mix-icon"},"Mix",{G:"span",L:"ytp-videowall-still-listlabel-length",oa:" (50+)"}]}]});this.suggestion=null;this.u=d;this.api=a;this.j=new g.iA(this);g.H(this,this.j);this.Ma("click",this.onClick);this.Ma("keypress",this.onKeyPress);this.j.T(a,"videodatachange",this.onVideoDataChange);a.Qh(this.element,this);this.onVideoDataChange()},z3=function(a){s3.call(this,a,"videowall-endscreen");
var b=this;this.I=a;this.B=0;this.stills=[];this.C=this.videoData=null;this.D=this.K=!1;this.S=null;this.u=new g.iA(this);g.H(this,this.u);this.J=new g.L(function(){g.M(b.element,"ytp-show-tiles")},0);
g.H(this,this.J);var c=new g.V({G:"button",Ea:["ytp-button","ytp-endscreen-previous"],W:{"aria-label":"Previous"},U:[g.cH()]});g.H(this,c);c.Ba(this.element);c.Ma("click",this.cU,this);this.table=new g.VG({G:"div",L:"ytp-endscreen-content"});g.H(this,this.table);this.table.Ba(this.element);c=new g.V({G:"button",Ea:["ytp-button","ytp-endscreen-next"],W:{"aria-label":"Next"},U:[g.dH()]});g.H(this,c);c.Ba(this.element);c.Ma("click",this.bU,this);a.getVideoData().ud?this.j=new o3(a,!0):this.j=new t3(a);
g.H(this,this.j);g.EJ(this.player,this.j.element,4);this.hide()},A3=function(a){return g.FJ(a.player)&&a.ax()&&!a.C},B3=function(a){var b=a.We();
b!==a.K&&(a.K=b,a.player.ea("autonavvisibility"))},C3=function(a){g.cK.call(this,a);
var b=this;this.endScreen=null;this.j=this.u=this.B=!1;this.listeners=new g.iA(this);g.H(this,this.listeners);this.env=a.V();xWa(a)?(this.B=!0,yWa(this),this.j?this.endScreen=new v3(a):this.endScreen=new z3(this.player)):this.env.Pe?this.endScreen=new x3(this.player):this.endScreen=new s3(this.player);g.H(this,this.endScreen);g.EJ(this.player,this.endScreen.element,4);zWa(this);this.listeners.T(a,"videodatachange",this.onVideoDataChange,this);this.listeners.T(a,g.Lw("endscreen"),function(c){b.onCueRangeEnter(c)});
this.listeners.T(a,g.Mw("endscreen"),function(c){b.onCueRangeExit(c)})},yWa=function(a){var b=a.player.getVideoData();
if(!b||a.j===b.Si&&a.u===b.ud)return!1;a.j=b.Si;a.u=b.ud;return!0},xWa=function(a){a=a.V();
return!a.C&&a.Kc&&!a.Pe},zWa=function(a){a.player.Nf("endscreen");
var b=a.player.getVideoData();b=new g.Jw(Math.max(1E3*(b.lengthSeconds-10),0),0x8000000000000,{id:"preload",namespace:"endscreen"});var c=new g.Jw(0x8000000000000,0x8000000000000,{id:"load",priority:8,namespace:"endscreen"});a.player.je([b,c])};
g.xJ.prototype.qr=g.ca(4,function(){return this.app.qr()});
g.CT.prototype.qr=g.ca(3,function(){return this.getVideoData().aQ});g.w(m3,g.V);m3.prototype.select=function(){(this.I.ll(this.suggestion.videoId,this.suggestion.sessionData,this.suggestion.playlistId,void 0,void 0,this.suggestion.yx||void 0)||this.I.N("web_player_endscreen_double_log_fix_killswitch"))&&this.I.ub(this.element)};
m3.prototype.onClick=function(a){g.BK(a,this.I,this.j,this.suggestion.sessionData||void 0)&&this.select()};
m3.prototype.onKeyPress=function(a){switch(a.keyCode){case 13:case 32:g.wu(a)||(this.select(),g.vu(a))}};g.w(o3,g.V);g.h=o3.prototype;g.h.oA=function(a){this.suggestion!==a&&(this.suggestion=a,l3(this.j,a),this.playButton.Ka("url",this.suggestion.Zl()),r3(this))};
g.h.Qi=function(){return 0<this.u};
g.h.Mv=function(){this.Qi()||(this.u=Date.now(),n3(this),vWa(this.I,q3(this)),g.O(this.I.getRootNode(),"countdown-running",this.Qi()))};
g.h.qs=function(){this.xo();n3(this);var a=this.j.Ca("ytp-autonav-endscreen-upnext-header");a&&g.ji(a,"Up next")};
g.h.xo=function(){this.Qi()&&(this.C.stop(),this.u=0)};
g.h.select=function(a){this.I.nextVideo(!1,void 0===a?!1:a);this.xo()};
g.h.ZK=function(a){g.BK(a,this.I)&&(a.currentTarget===this.playButton.element?this.I.ub(this.playButton.element):a.currentTarget===this.j.Ca("ytp-autonav-endscreen-link-container")&&(a=this.j.Ca("ytp-autonav-endscreen-link-container"),this.I.Wa(a,!0),this.I.ub(a)),this.select())};
g.h.UT=function(){this.I.ub(this.cancelButton.element);g.zJ(this.I,!0);this.D&&this.I.Oa("innertubeCommand",this.D)};
g.h.onVideoDataChange=function(a,b){var c;this.D=null==(c=b.f1)?void 0:c.command};
g.h.YK=function(){var a=this.I.We();this.J&&this.sb!==a&&g.YG(this,a);r3(this);this.I.Wa(this.element,a);this.I.Wa(this.cancelButton.element,a);this.I.Wa(this.j.Ca("ytp-autonav-endscreen-link-container"),a);this.I.Wa(this.playButton.element,a)};
g.h.gg=function(a){return 400>a.width||459>a.height};g.w(s3,g.V);g.h=s3.prototype;g.h.create=function(){this.created=!0};
g.h.destroy=function(){this.created=!1};
g.h.ax=function(){return!1};
g.h.We=function(){return!1};
g.h.rO=function(){return!1};g.w(t3,g.V);g.h=t3.prototype;g.h.OA=function(){this.notification&&(this.C.stop(),this.xc(this.B),this.B=null,this.notification.close(),this.notification=null)};
g.h.oA=function(a){this.suggestion=a;l3(this,a,"hqdefault.jpg")};
g.h.aL=function(){g.YG(this,this.api.We());this.api.Wa(this.element,this.api.We());this.api.Wa(this.Ca("ytp-upnext-autoplay-icon"),this.api.We());this.cancelButton&&this.api.Wa(this.cancelButton.element,this.api.We())};
g.h.OY=function(){window.focus();this.OA()};
g.h.Mv=function(a){var b=this;this.Qi()||(g.Ku("a11y-announce","Up Next "+this.suggestion.title),this.u=(0,g.R)(),this.j=new g.L(function(){u3(b,a)},25),u3(this,a),vWa(this.api,wWa(this,a)));
g.Hp(this.element,"ytp-upnext-autoplay-paused")};
g.h.hide=function(){g.V.prototype.hide.call(this)};
g.h.Qi=function(){return!!this.j};
g.h.qs=function(){this.xo();this.u=(0,g.R)();u3(this);g.M(this.element,"ytp-upnext-autoplay-paused")};
g.h.xo=function(){this.Qi()&&(this.j.dispose(),this.j=null)};
g.h.select=function(a){a=void 0===a?!1:a;if(this.api.V().N("autonav_notifications")&&a&&window.Notification&&"function"===typeof document.hasFocus){var b=Notification.permission;"default"===b?Notification.requestPermission():"granted"!==b||document.hasFocus()||(this.OA(),this.notification=new Notification("Up Next",{body:this.suggestion.title,icon:this.suggestion.zf()}),this.B=this.T(this.notification,"click",this.OY),this.C.start())}this.xo();this.api.nextVideo(!1,a)};
g.h.XT=function(a){!g.ii(this.cancelButton.element,g.qu(a))&&g.BK(a,this.api)&&(this.api.We()&&this.api.ub(this.Ca("ytp-upnext-autoplay-icon")),this.select())};
g.h.VT=function(){this.api.We()&&this.cancelButton&&this.api.ub(this.cancelButton.element);g.zJ(this.api,!0)};
g.h.EY=function(a){this.api.getPresentingPlayerType();this.show();this.Mv(a)};
g.h.FY=function(){this.api.getPresentingPlayerType();this.xo();this.hide()};
g.h.qa=function(){this.xo();this.OA();g.V.prototype.qa.call(this)};g.w(v3,s3);g.h=v3.prototype;g.h.create=function(){s3.prototype.create.call(this);this.C.T(this.player,"appresize",this.Dw);this.C.T(this.player,"onVideoAreaChange",this.Dw);this.C.T(this.player,"videodatachange",this.onVideoDataChange);this.C.T(this.player,"autonavchange",this.bL);this.C.T(this.player,"autonavcancel",this.ZT);this.onVideoDataChange()};
g.h.show=function(){s3.prototype.show.call(this);(this.J||this.B&&this.B!==this.videoData.clientPlaybackNonce)&&g.zJ(this.player,!1);g.FJ(this.player)&&this.ax()&&!this.B?(w3(this),2===this.videoData.autonavState?this.player.V().N("fast_autonav_in_background")&&3===this.player.getVisibilityState()?this.j.select(!0):this.j.Mv():3===this.videoData.autonavState&&this.j.qs()):(g.zJ(this.player,!0),w3(this));this.Dw()};
g.h.hide=function(){s3.prototype.hide.call(this);this.j.qs();w3(this)};
g.h.Dw=function(){var a=this.player.Ek(!0,this.player.isFullscreen());w3(this);r3(this.u);g.O(this.element,"ytp-autonav-cancelled-small-mode",this.gg(a));g.O(this.element,"ytp-autonav-cancelled-tiny-mode",this.SB(a));g.O(this.element,"ytp-autonav-cancelled-mini-mode",400>=a.width||360>=a.height);this.overlay&&g.Km(this.overlay.element,{width:a.width+"px"});if(!this.D){a=g.r(this.videos.entries());for(var b=a.next();!b.done;b=a.next()){var c=g.r(b.value);b=c.next().value;c=c.next().value;g.O(c.element,
"ytp-suggestion-card-with-margin",1===b%2)}}};
g.h.onVideoDataChange=function(){var a=this.player.getVideoData();if(this.videoData!==a&&a){this.videoData=a;if((a=this.videoData.suggestions)&&a.length){this.j.oA(a[0]);this.j!==this.u&&this.u.oA(a[0]);for(var b=0;b<AWa.length;++b){var c=AWa[b];if(a&&a[c]){this.videos[b]=new m3(this.player);var d=this.videos[b];c=a[c];d.suggestion!==c&&(d.suggestion=c,l3(d,c));g.H(this,this.videos[b]);this.videos[b].Ba(this.K.element)}}}this.Dw()}};
g.h.bL=function(a){1===a?(this.J=!1,this.B=this.videoData.clientPlaybackNonce,this.j.xo(),this.sb&&this.Dw()):(this.J=!0,this.We()&&(2===a?this.j.Mv():3===a&&this.j.qs()))};
g.h.ZT=function(a){a?this.bL(1):(this.B=null,this.J=!1)};
g.h.ax=function(){return 1!==this.videoData.autonavState};
g.h.gg=function(a){return(910>a.width||459>a.height)&&!this.SB(a)&&!(400>=a.width||360>=a.height)};
g.h.SB=function(a){return 800>a.width&&!(400>=a.width||360>=a.height)};
g.h.We=function(){return this.sb&&g.FJ(this.player)&&this.ax()&&!this.B};
var AWa=[1,3,2,4];g.w(x3,s3);x3.prototype.Ha=function(){var a=this.player.getVideoData();this.j.update({profilePicture:a.profilePicture,author:a.author});this.subscribeButton.channelId=a.Zj;var b=this.subscribeButton;a.subscribed?b.u():b.B()};g.w(y3,g.V);y3.prototype.select=function(){(this.api.ll(this.suggestion.videoId,this.suggestion.sessionData,this.suggestion.playlistId,void 0,void 0,this.suggestion.yx||void 0)||this.api.N("web_player_endscreen_double_log_fix_killswitch"))&&this.api.ub(this.element)};
y3.prototype.onClick=function(a){g.BK(a,this.api,this.u,this.suggestion.sessionData||void 0)&&this.select()};
y3.prototype.onKeyPress=function(a){switch(a.keyCode){case 13:case 32:g.wu(a)||(this.select(),g.vu(a))}};
y3.prototype.onVideoDataChange=function(){var a=this.api.getVideoData(),b=this.api.V();this.u=a.D?!1:b.j};g.w(z3,s3);g.h=z3.prototype;g.h.create=function(){s3.prototype.create.call(this);var a=this.player.getVideoData();a&&(this.videoData=a);this.Nm();this.u.T(this.player,"appresize",this.Nm);this.u.T(this.player,"onVideoAreaChange",this.Nm);this.u.T(this.player,"videodatachange",this.onVideoDataChange);this.u.T(this.player,"autonavchange",this.tE);this.u.T(this.player,"autonavcancel",this.aU);a=this.videoData.autonavState;a!==this.S&&this.tE(a);this.u.T(this.element,"transitionend",this.b_)};
g.h.destroy=function(){g.hv(this.u);g.of(this.stills);this.stills=[];s3.prototype.destroy.call(this);g.Hp(this.element,"ytp-show-tiles");this.J.stop();this.S=this.videoData.autonavState};
g.h.ax=function(){return 1!==this.videoData.autonavState};
g.h.show=function(){s3.prototype.show.call(this);g.Hp(this.element,"ytp-show-tiles");this.player.V().isMobile?g.Ap(this.J):this.J.start();(this.D||this.C&&this.C!==this.videoData.clientPlaybackNonce)&&g.zJ(this.player,!1);A3(this)?(B3(this),2===this.videoData.autonavState?this.player.V().N("fast_autonav_in_background")&&3===this.player.getVisibilityState()?this.j.select(!0):this.j.Mv():3===this.videoData.autonavState&&this.j.qs()):(g.zJ(this.player,!0),B3(this))};
g.h.hide=function(){s3.prototype.hide.call(this);this.j.qs();B3(this)};
g.h.b_=function(a){g.qu(a)===this.element&&this.Nm()};
g.h.Nm=function(){if(this.videoData&&this.videoData.suggestions&&this.videoData.suggestions.length){g.M(this.element,"ytp-endscreen-paginate");var a=this.I.Ek(!0,this.I.isFullscreen()),b=g.uJ(this.I);b&&(b=b.If()?48:32,a.width-=2*b);var c=a.width/a.height,d=96/54,e=b=2,f=Math.max(a.width/96,2),k=Math.max(a.height/54,2),l=this.videoData.suggestions.length,m=Math.pow(2,2);var n=l*m+(Math.pow(2,2)-m);n+=Math.pow(2,2)-m;for(n-=m;0<n&&(b<f||e<k);){var p=b/2,q=e/2,t=b<=f-2&&n>=q*m,v=e<=k-2&&n>=p*m;if((p+
1)/q*d/c>c/(p/(q+1)*d)&&v)n-=p*m,e+=2;else if(t)n-=q*m,b+=2;else if(v)n-=p*m,e+=2;else break}d=!1;n>=3*m&&6>=l*m-n&&(4<=e||4<=b)&&(d=!0);m=96*b;n=54*e;c=m/n<c?a.height/n:a.width/m;c=Math.min(c,2);m=Math.floor(Math.min(a.width,m*c));n=Math.floor(Math.min(a.height,n*c));a=this.table.element;g.Um(a,m,n);g.Km(a,{marginLeft:m/-2+"px",marginTop:n/-2+"px"});this.j.oA(this.videoData.suggestions[0]);this.j instanceof o3&&r3(this.j);g.O(this.element,"ytp-endscreen-takeover",A3(this));B3(this);m+=4;n+=4;for(f=
c=0;f<b;f++)for(k=0;k<e;k++)if(q=c,p=0,d&&f>=b-2&&k>=e-2?p=1:0===k%2&&0===f%2&&(2>k&&2>f?0===k&&0===f&&(p=2):p=2),q=g.th(q+this.B,l),0!==p){t=this.stills[c];t||(t=new y3(this.player),this.stills[c]=t,a.appendChild(t.element));v=Math.floor(n*k/e);var x=Math.floor(m*f/b),y=Math.floor(n*(k+p)/e)-v-4,z=Math.floor(m*(f+p)/b)-x-4;g.Qm(t.element,x,v);g.Um(t.element,z,y);g.Km(t.element,"transitionDelay",(k+f)/20+"s");g.O(t.element,"ytp-videowall-still-mini",1===p);g.O(t.element,"ytp-videowall-still-large",
2<p);p=t;q=this.videoData.suggestions[q];p.suggestion!==q&&(p.suggestion=q,t=p.api.V(),v=g.Fp(p.element,"ytp-videowall-still-large")?"hqdefault.jpg":"mqdefault.jpg",l3(p,q,v),g.rC(t)&&(v=q.Zl(),x={},t.ra&&g.RI(x,t.loaderUrl),v=g.sj(v,g.QI(x,"emb_rel_end")),p.Ka("url",v)),(q=(q=q.sessionData)&&q.itct)&&p.api.al(p.element,q));c++}g.O(this.element,"ytp-endscreen-paginate",c<l);for(b=this.stills.length-1;b>=c;b--)e=this.stills[b],g.gi(e.element),g.nf(e);this.stills.length=c}};
g.h.onVideoDataChange=function(){var a=this.player.getVideoData();this.videoData!==a&&(this.B=0,this.videoData=a,this.Nm())};
g.h.bU=function(){this.B+=this.stills.length;this.Nm()};
g.h.cU=function(){this.B-=this.stills.length;this.Nm()};
g.h.rO=function(){return this.j.Qi()};
g.h.tE=function(a){1===a?(this.D=!1,this.C=this.videoData.clientPlaybackNonce,this.j.xo(),this.sb&&this.Nm()):(this.D=!0,this.sb&&A3(this)&&(2===a?this.j.Mv():3===a&&this.j.qs()))};
g.h.aU=function(a){if(a){for(a=0;a<this.stills.length;a++)this.I.Wa(this.stills[a].element,!0);this.tE(1)}else this.C=null,this.D=!1;this.Nm()};
g.h.We=function(){return this.sb&&A3(this)};g.w(C3,g.cK);g.h=C3.prototype;g.h.Is=function(){var a=this.player.getVideoData(),b=!!(a&&a.suggestions&&a.suggestions.length);b=!xWa(this.player)||b;var c=a.qf||g.CC(a.B),d=this.player.Fx();a=a.mutedAutoplay;return b&&!c&&!d&&!a};
g.h.We=function(){return this.endScreen.We()};
g.h.EW=function(){return this.We()?this.endScreen.rO():!1};
g.h.qa=function(){this.player.Nf("endscreen");g.cK.prototype.qa.call(this)};
g.h.load=function(){var a=this.player.getVideoData();var b=a.fP;if(b&&b.videoId){var c=this.player.ob().Zd.get("heartbeat");a&&a.suggestions&&a.suggestions.length&&b.videoId===a.suggestions[0].videoId&&!a.IL?a=!1:(this.player.ll(b.videoId,void 0,void 0,!0,!0,b),c&&c.aC("HEARTBEAT_ACTION_TRIGGER_AT_STREAM_END","HEARTBEAT_ACTION_TRANSITION_REASON_HAS_NEW_STREAM_TRANSITION_ENDPOINT"),a=!0)}else a=!1;a||(g.cK.prototype.load.call(this),this.endScreen.show())};
g.h.unload=function(){g.cK.prototype.unload.call(this);this.endScreen.hide();this.endScreen.destroy()};
g.h.onCueRangeEnter=function(a){this.Is()&&(this.endScreen.created||this.endScreen.create(),"load"===a.getId()&&this.load())};
g.h.onCueRangeExit=function(a){"load"===a.getId()&&this.loaded&&this.unload()};
g.h.onVideoDataChange=function(){zWa(this);this.B&&yWa(this)&&(this.endScreen&&(this.endScreen.hide(),this.endScreen.created&&this.endScreen.destroy(),this.endScreen.dispose()),this.j?this.endScreen=new v3(this.player):this.endScreen=new z3(this.player),g.H(this,this.endScreen),g.EJ(this.player,this.endScreen.element,4))};g.bK("endscreen",C3);})(_yt_player);
