(function(g){var window=this;/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
'use strict';var D3=function(a,b){if(!Number.isFinite(a))return String(a);a=String(a);var c=a.indexOf(".");-1===c&&(c=a.length);var d="-"===a[0]?"-":"";d&&(a=a.substring(1));return d+(0,g.DRa)("0",Math.max(0,b-c))+a},BWa=function(){return{G:"svg",
W:{fill:"#fff",height:"24px",viewBox:"0 0 24 24",width:"24px"},U:[{G:"path",W:{d:"M12 22c1.1 0 2-.9 2-2h-4c0 1.1.9 2 2 2zm6-6v-5c0-3.07-1.64-5.64-4.5-6.32V4c0-.83-.67-1.5-1.5-1.5s-1.5.67-1.5 1.5v.68C7.63 5.36 6 7.92 6 11v5l-2 2v1h16v-1l-2-2z"}}]}},CWa=function(){return{G:"svg",
W:{fill:"#fff",height:"24px",viewBox:"0 0 24 24",width:"24px"},U:[{G:"path",W:{d:"M12 22c1.1 0 2-.9 2-2h-4c0 1.1.9 2 2 2zm6-6v-5c0-3.07-1.63-5.64-4.5-6.32V4c0-.83-.67-1.5-1.5-1.5s-1.5.67-1.5 1.5v.68C7.64 5.36 6 7.92 6 11v5l-2 2v1h16v-1l-2-2zm-2 1H8v-6c0-2.48 1.51-4.5 4-4.5s4 2.02 4 4.5v6z"}}]}},F3=function(a){"number"===typeof a?(this.date=DWa(a,0,1),E3(this,1)):g.Ma(a)?(this.date=DWa(a.getFullYear(),a.getMonth(),a.getDate()),E3(this,a.getDate())):(this.date=new Date(g.Ta()),a=this.date.getDate(),
this.date.setHours(0),this.date.setMinutes(0),this.date.setSeconds(0),this.date.setMilliseconds(0),E3(this,a))},DWa=function(a,b,c){b=new Date(a,b,c);
0<=a&&100>a&&b.setFullYear(b.getFullYear()-1900);return b},E3=function(a,b){a.getDate()!=b&&a.date.setUTCHours(a.date.getUTCHours()+(a.getDate()<b?1:-1))},G3=function(a,b){g.OK.call(this,a,{G:"div",
L:"ytp-reminder-menu",W:{role:"menu",tabindex:"-1"},U:[{G:"div",L:"ytp-reminder-menu-contents",U:[{G:"div",L:"ytp-reminder-menu-items"}]}]},100,!0);this.buttonElement=b;this.j=[];this.menuPopupRenderer=void 0;this.items=this.Ca("ytp-reminder-menu-items");this.hide()},FWa=function(a){var b=EWa(a),c=0,d={};
for(c=0;c<b.length;d={FD:d.FD},c++){var e=a.j[c];e||(e=new g.V({G:"div",L:"ytp-reminder-menu-item",W:{role:"menuitem",tabindex:"0"},U:[{G:"div",L:"ytp-reminder-menu-item-icon",oa:"{{icon}}"},{G:"div",L:"ytp-reminder-menu-item-label",oa:"{{text}}"}]}),d.FD=c,e.Ma("click",function(l){return function(){var m=l.FD;a.Gb();m=EWa(a)[m];a.ea("reminderMenuItemClicked",m.serviceEndpoint||m.command)}}(d)),e.Ba(a.items),a.j[c]=e);
var f=b[c],k=null;switch(f.icon&&f.icon.iconType){case "NOTIFICATIONS":k=BWa();break;case "NOTIFICATIONS_NONE":k=CWa();break;case "NOTIFICATIONS_ACTIVE":k=g.iH()}f=f.text?g.Qw(f.text):"";e.update({icon:k,text:f})}for(;c<a.j.length;)a.j.pop().dispose();0===c?a.Gb():a.yd(a.buttonElement)},EWa=function(a){return(a.menuPopupRenderer&&a.menuPopupRenderer.items||[]).reduce(function(b,c){c&&c.menuServiceItemRenderer&&b.push(c.menuServiceItemRenderer);
return b},[])},H3=function(a){g.V.call(this,{G:"div",
U:[{G:"button",Ea:["ytp-offline-slate-button","ytp-button"],U:[{G:"div",L:"ytp-offline-slate-button-icon",oa:"{{icon}}"},{G:"div",L:"ytp-offline-slate-button-text",oa:"{{text}}"}]}]});this.I=a;this.upcomingEventReminderButtonRenderer=this.toggleButtonRenderer=null;this.u=void 0;this.C=this.j=null;(this.buttonElement=this.Ca("ytp-offline-slate-button"))&&this.T(this.buttonElement,"click",this.D);this.hide()},GWa=function(a,b,c){!a.toggleButtonRenderer&&b&&b.toggleButtonRenderer?a.toggleButtonRenderer=
b.toggleButtonRenderer:b&&b.toggleButtonRenderer||(a.toggleButtonRenderer=null);
!a.upcomingEventReminderButtonRenderer&&c&&c.upcomingEventReminderButtonRenderer?a.upcomingEventReminderButtonRenderer=c.upcomingEventReminderButtonRenderer:c&&c.upcomingEventReminderButtonRenderer||(a.upcomingEventReminderButtonRenderer=null);I3(a)},I3=function(a){if(a.toggleButtonRenderer){var b=a.toggleButtonRenderer;
if(b.isToggled){var c=b.toggledText?g.Qw(b.toggledText):"";a.update({text:c,icon:J3(b.toggledIcon)})}else c=b.defaultText?g.Qw(b.defaultText):"",a.update({text:c,icon:J3(b.defaultIcon)});a.show()}else a.upcomingEventReminderButtonRenderer?(b=HWa(a))?(c=b.text?g.Qw(b.text):"",a.update({text:c,icon:J3(b.icon)}),a.show()):a.hide():a.hide()},JWa=function(a,b,c){a.C||(a.C=new g.iu(a.I.V().Uh));
var d={context:g.ws(a.C.config_||g.vs())};g.Tv()&&(d.context.clientScreenNonce=g.Tv());d.params=c;g.ju(a.C,b,d,{timeout:5E3,onSuccess:function(){a.upcomingEventReminderButtonRenderer&&a.u&&(a.upcomingEventReminderButtonRenderer.currentState=a.u,a.u=void 0)},
onError:function(){IWa(a)},
onTimeout:function(){IWa(a)}})},IWa=function(a){a.toggleButtonRenderer?(a.toggleButtonRenderer.isToggled=!a.toggleButtonRenderer.isToggled,I3(a)):a.upcomingEventReminderButtonRenderer&&(a.u=void 0,I3(a))},J3=function(a){if(!a)return null;
switch(a.iconType){case "NOTIFICATIONS":return BWa();case "NOTIFICATIONS_NONE":return CWa();case "NOTIFICATIONS_ACTIVE":return g.iH();default:return null}},HWa=function(a){if(!a.upcomingEventReminderButtonRenderer)return null;
var b=a.u||a.upcomingEventReminderButtonRenderer.currentState;a=g.r(a.upcomingEventReminderButtonRenderer.states||[]);for(var c=a.next();!c.done;c=a.next())if((c=c.value.upcomingEventReminderButtonStateRenderer)&&c.state===b&&c.button&&c.button.buttonRenderer)return c.button.buttonRenderer;return null},K3=function(a){g.V.call(this,{G:"div",
L:"ytp-offline-slate",U:[{G:"div",L:"ytp-offline-slate-background"},{G:"div",L:"ytp-offline-slate-bar",U:[{G:"span",L:"ytp-offline-slate-icon",U:[{G:"svg",W:{fill:"#fff",height:"100%",viewBox:"0 0 24 24",width:"100%"},U:[{G:"path",W:{d:"M16.94 6.91l-1.41 1.45c.9.94 1.46 2.22 1.46 3.64s-.56 2.71-1.46 3.64l1.41 1.45c1.27-1.31 2.05-3.11 2.05-5.09s-.78-3.79-2.05-5.09zM19.77 4l-1.41 1.45C19.98 7.13 21 9.44 21 12.01c0 2.57-1.01 4.88-2.64 6.54l1.4 1.45c2.01-2.04 3.24-4.87 3.24-7.99 0-3.13-1.23-5.96-3.23-8.01zM7.06 6.91c-1.27 1.3-2.05 3.1-2.05 5.09s.78 3.79 2.05 5.09l1.41-1.45c-.9-.94-1.46-2.22-1.46-3.64s.56-2.71 1.46-3.64L7.06 6.91zM5.64 5.45L4.24 4C2.23 6.04 1 8.87 1 11.99c0 3.13 1.23 5.96 3.23 8.01l1.41-1.45C4.02 16.87 3 14.56 3 11.99s1.01-4.88 2.64-6.54z"}},
{G:"circle",W:{cx:"12",cy:"12",r:"3"}}]}]},{G:"span",L:"ytp-offline-slate-messages",U:[{G:"div",L:"ytp-offline-slate-main-text",W:{"aria-label":"{{label}}"},oa:"{{mainText}}"},{G:"div",L:"ytp-offline-slate-subtitle-text",oa:"{{subtitleText}}"}]},{G:"span",L:"ytp-offline-slate-buttons"}]},{G:"button",Ea:["ytp-offline-slate-close-button","ytp-button"],U:[g.dH()]},{G:"button",Ea:["ytp-offline-slate-open-button","ytp-button"],U:[g.cH()]},{G:"div",L:"ytp-offline-slate-trailer-chip",oa:"Trailer"}]});var b=
this;this.api=a;this.j=this.u=null;this.background=this.Ca("ytp-offline-slate-background");this.B=this.Ca("ytp-offline-slate-bar");this.D=new g.L(function(){g.M(b.B,"ytp-offline-slate-bar-fade")},15E3);
this.J=!1;this.C=new g.L(function(){g.M(b.element,"ytp-offline-slate-collapsed")},15E3);
g.H(this,this.C);g.H(this,this.D);this.countdownTimer=new g.L(this.HR,1E3,this);this.T(a,"presentingplayerstatechange",this.KR);this.T(a,"livestatedata",this.Ha);a=this.Ca("ytp-offline-slate-close-button");this.T(a,"click",function(){g.M(b.element,"ytp-offline-slate-collapsed")});
a=this.Ca("ytp-offline-slate-open-button");this.T(a,"click",function(){g.Hp(b.element,"ytp-offline-slate-collapsed")});
this.hide();a=this.getVideoData();a.getPlayerResponse()&&(a=a.getPlayerResponse().playabilityStatus)&&this.Ha(a);a=8===this.api.getPresentingPlayerType()&&!this.getVideoData().Wj;var c=8===this.api.getPresentingPlayerType();g.O(this.element,"ytp-offline-slate-premiere-trailer",a);g.O(this.element,"ytp-offline-slate-hide-background",c)},L3=function(a,b,c){if(b){var d=null!=b.subtitleText?g.Qw(b.subtitleText):"";
c=c?c:null!=b.mainText?g.Qw(b.mainText):"";var e,f,k,l;b=null!=(l=null==(e=b.mainText)?void 0:null==(f=e.accessibility)?void 0:null==(k=f.accessibilityData)?void 0:k.label)?l:c;a.update({mainText:c,subtitleText:d,label:b});g.O(a.element,"ytp-offline-slate-single-text-line",!d);g.O(a.B,"ytp-offline-slate-bar-hidden",!c&&!d)}},M3=function(a,b){var c=(0,g.R)();
this.trigger=a;this.j=b;this.B=c},O3=function(a){g.cK.call(this,a);
var b=this;this.K=!1;this.S=0;this.D=!1;this.u=new g.L(function(){var e=b.player.V(),f=b.getVideoData();N3(b)&&(KWa(b)?LWa(b,e,f):(MWa(b),NWa(b,e,f)))},0);
this.j=this.heartbeatParams=null;this.C=!1;this.J=new g.Ti(1E3,6E4,1);this.sequenceNumber=0;this.offlineSlate=null;this.Z=new g.iu(void 0);this.Y=this.attestationResponse=void 0;this.utcOffsetMinutes=-(new F3).date.getTimezoneOffset();this.B=new g.iA(this);g.H(this,this.u);g.H(this,this.B);MWa(this);OWa(this);this.B.T(a,"heartbeatparams",this.Qy);this.B.T(a,"presentingplayerstatechange",this.dU);this.B.T(a,"videoplayerreset",this.eU);this.B.T(a,g.Lw("heartbeat"),this.onCueRangeEnter);this.C&&this.j&&
PWa(this,this.j);var c=new g.Jw(1E3,0x7ffffffffffff,{priority:1,namespace:"heartbeat"}),d=new g.Jw(0x8000000000000,0x8000000000000,{id:"stream_end",priority:1,namespace:"heartbeat"});a.je([c,d]);QWa(this)},QWa=function(a){var b=a.getVideoData();
b.Ri&&(b=b.botguardData)&&g.OI(b,a.player.V())},MWa=function(a){var b=a.getVideoData();
if(b.Ri&&(b=new g.AAa(b),g.KI.isInitialized()||3<=a.sequenceNumber)){var c=null;if(b.videoData.Xa){var d=g.BAa(b);if(d){c={};var e={};d=d.split("&");d=g.r(d);for(var f=d.next();!f.done;f=d.next())f=f.value.split("="),2===f.length&&(e[f[0]]=f[1]);e.r1a&&(c.webResponse=e.r1a);e.r1c&&(c.error=RWa[Number(e.r1c)]);c.challenge=b.videoData.Xa}}a.attestationResponse=c||void 0}},KWa=function(a){var b=a.getVideoData();
if(!g.kE(a.getVideoData())||b.dK)return!1;if(b.useInnertubeDrmService()&&b.Y){a="playready"===b.Y.flavor&&b.N("html5_innertube_heartbeats_for_playready");var c="widevine"===b.Y.flavor&&b.N("html5_innertube_heartbeats_for_widevine");b=g.rB(b.Y)&&b.N("html5_innertube_heartbeats_for_fairplay");return!(a||c||b)}return!0},P3=function(a){if(KWa(a))return!!a.heartbeatParams;
var b=a.player.V(),c=a.getVideoData();return b.N("html5_heartbeat_wait_for_drm_killswitch")||!g.kE(a.getVideoData())||!c.useInnertubeDrmService()||c.Tg||c.fH?!!c.heartbeatToken:!1},Q3=function(a,b){if(!a.u.isActive()&&a.K){var c=a.getVideoData();
if(P3(a)||c.isLivePlayback){if(void 0===b)if(a.D)if(a.C)b=7500;else{var d;b=(null==(d=a.heartbeatParams)?0:d.interval)?1E3*a.heartbeatParams.interval:a.getVideoData().ZJ||6E4}else b=1E3;a.u.start(b)}}},VWa=function(a,b,c){b.nk&&(c=g.sj(c,{internalipoverride:b.nk}));
var d={cpn:b.clientPlaybackNonce};b.contextParams&&(d.context_params=b.contextParams);b.Kb&&(d.kpt=b.Kb);c=g.sj(c,d);g.Gr(c,{format:"RAW",method:"GET",timeout:3E4,onSuccess:function(e){if(!a.u.isActive()&&N3(a)){a.J.reset();a.sequenceNumber++;e=e.responseText;var f=SWa(e);if(f){a.player.Oa("onHeartbeat",f);var k="ok"===f.status?f.stop_heartbeat?2:0:"stop"===f.status?1:"live_stream_offline"===f.status?0:-1}else k=(k=e.match(TWa))?"0"===k[1]?0:1:-1;UWa(a,f,e,k)}},
onError:function(e){N3(a)&&R3(a,!0,"net-"+e.status)},
onTimeout:function(){N3(a)&&R3(a,!0,"timeout")},
withCredentials:!0})},LWa=function(a,b,c){var d;
if(null!=(d=a.heartbeatParams)&&d.url){var e=g.sj(a.heartbeatParams.url,{request_id:g.rpa()});c.Ta&&(e=g.sj(e,{vvt:c.Ta}),c.mdxEnvironment&&(e=g.sj(e,{mdx_environment:c.mdxEnvironment})));g.cD(b,c.oauthToken).then(function(f){f&&(e=g.sj(e,{access_token:f}));VWa(a,c,e)})}},N3=function(a){var b=a.getVideoData();
return 3===a.player.getPresentingPlayerType()||g.U(a.player.yb(a.getPlayerType()),4)?!1:P3(a)||b.isLivePlayback?!0:(S3(a),!1)},NWa=function(a,b,c){var d,e={videoId:c.videoId,
sequenceNumber:a.sequenceNumber,heartbeatServerData:null!=(d=a.ma)?d:c.heartbeatServerData};a.Y=a.attestationResponse;c.Ri&&(e.attestationResponse=a.Y);var f=g.TI(c),k;d=null!=(k=f.client)?k:{};d.utcOffsetMinutes=a.utcOffsetMinutes;e.context=f;e.cpn=c.clientPlaybackNonce;if(k="undefined"!==typeof Intl?(new Intl.DateTimeFormat).resolvedOptions().timeZone:null)d.timeZone=k;k={heartbeatChecks:[]};if(d=c.getPlayerResponse())c.heartbeatToken&&(e.heartbeatToken=c.heartbeatToken),(d=d.playabilityStatus)&&
(d=d.liveStreamability)&&d.liveStreamabilityRenderer&&k.heartbeatChecks.push("HEARTBEAT_CHECK_TYPE_LIVE_STREAM_STATUS");c.heartbeatToken&&k.heartbeatChecks.push("HEARTBEAT_CHECK_TYPE_YPC");if(g.TC(b)){k.heartbeatChecks.push("HEARTBEAT_CHECK_TYPE_UNPLUGGED");f=WWa(a);d={};null!==f&&(d.clientPlayerPositionUtcMillis=f);var l,m;f=(null==(m=null==(l=a.player.ob())?void 0:g.rK(l))?void 0:m.freePreviewWatchedDuration)||0;0<f&&(d.freePreviewWatchedDuration={seconds:""+f});k.unpluggedParams=d}e.heartbeatRequestParams=
k;b.N("enable_linear_player_handling")&&c.isLivePlayback&&(l=WWa(a),null!==l&&(e.playbackState||(e.playbackState={}),e.playbackState.playbackPosition={utcTimeMillis:l}));var n={timeout:3E4,onSuccess:function(p){if(!a.u.isActive()&&N3(a)){var q=a.getVideoData(),t=q.Ri&&null==a.Y,v;q.Ri=!(null==(v=p.heartbeatAttestationConfig)||!v.requiresAttestation)||t;q=p.playabilityStatus;t=JSON.stringify(q)||"{}";p.authenticationMismatch&&a.player.xa("authshear",{});v=-1;var x=p.playabilityStatus;x&&(a.player.Oa("onHeartbeat",
x),"OK"===x.status?v=p.stopHeartbeat?2:0:"UNPLAYABLE"===x.status?v=1:"LIVE_STREAM_OFFLINE"===x.status&&(v=0));a.sequenceNumber&&-1===v||a.J.reset();a.sequenceNumber++;p.heartbeatServerData&&(a.ma=p.heartbeatServerData);UWa(a,q,t,v)}},
onError:function(p){N3(a)&&R3(a,!0,"net-"+p.status)},
onTimeout:function(){N3(a)&&R3(a,!0,"timeout")}};
g.cD(b,g.BE(c)).then(function(p){p&&(n.lM="Bearer "+p);g.ju(a.Z,"player/heartbeat",e,n)})},UWa=function(a,b,c,d){-1===d?(b="decode "+g.xc(c),R3(a,!1,b)):2===d?(S3(a),a.D=!0):(a.S=0,a.u.stop(),1===d?(a.D=!1,a.player.rg("heartbeat.stop",2,a.jf(c)),g.Ds("heartbeatActionPlayerHalted",XWa(b))):(a.D=!0,c=0,a.C&&b&&(c=PWa(a,b),a.player.ea("livestatedata",b)),c?Q3(a,c):Q3(a)))},PWa=function(a,b){var c=b.liveStreamability&&b.liveStreamability.liveStreamabilityRenderer,d=!(!c||!(c.switchStreamsImmediately||
c.transitionTiming&&"STREAM_TRANSITION_TIMING_IMMEDIATELY"===c.transitionTiming)),e=YWa(c),f=a.getVideoData(),k=a.player.yb(a.getPlayerType()),l=k.Nc()&&!g.pE(f)&&!a.player.isAtLiveHead(a.getPlayerType());
if(2<=f.V().Y){var m,n=(null==(m=a.player.Ld())?void 0:m.Pb())||{};n.status=b.status||"";n.dvr=""+ +l;n["switch"]=""+ +d;n.ended=""+ +!(!c||!c.displayEndscreen);a.player.xa("heartbeat",n)}if(l&&!d)return e;d=c&&c.streamTransitionEndpoint&&c.streamTransitionEndpoint.watchEndpoint;if("STREAM_TRANSITION_TIMING_AT_STREAM_END"===(c&&c.transitionTiming))a.getVideoData().fP=d;else{if(l=d)(l=d&&d.videoId)?(a.player.ll(l,{autonav:"1"},void 0,!0,!0,d),a.aC("HEARTBEAT_ACTION_TRIGGER_IMMEDIATE","HEARTBEAT_ACTION_TRANSITION_REASON_HAS_NEW_STREAM_TRANSITION_ENDPOINT",
b),l=!0):l=!1;if(l)return e}if("OK"===b.status.toUpperCase()){d=c&&c.broadcastId;l=a.j&&a.j.liveStreamability&&a.j.liveStreamability.liveStreamabilityRenderer&&a.j.liveStreamability.liveStreamabilityRenderer.broadcastId;m=d!==l&&(null!=d||a.player.N("web_player_heartbeat_undefined_killswitch"));if(!f.hlsvp&&!f.rb||m){var p={video_id:f.videoId};f.LJ&&(p.is_live_destination="1");a.player.N("web_player_heartbeat_request_watch_next")||(p.disable_watch_next=!0,p.raw_watch_next_response=f.watchNextResponse);
p.autonav_state=f.autonavState;p.oauth_token=f.oauthToken;p.force_gvi=f.Uh;p.zj=f.zj;c=void 0;f.hlsvp||f.rb?m&&(c=new M3("broadcastIdChanged",l+","+d),a.aC("HEARTBEAT_ACTION_TRIGGER_IMMEDIATE","HEARTBEAT_ACTION_TRANSITION_REASON_BROADCAST_ID_CHANGED",b)):(d&&(c=new M3("formatsReceived",""+d)),a.aC("HEARTBEAT_ACTION_TRIGGER_IMMEDIATE","HEARTBEAT_ACTION_TRANSITION_REASON_LIVE_STREAM_WENT_ONLINE",b));a.player.loadVideoByPlayerVars(p,void 0,void 0,void 0,c);return e}a.player.mf("heartbeat",a.getPlayerType())}c&&
c.displayEndscreen&&(a.offlineSlate?(a=a.offlineSlate,a.J=!0,a.sb&&a.api.Iv()):g.iG(k)&&(f=(null==(p=a.player.Ld())?void 0:p.Pb())||{},a.player.xa("hbse",f,!0),a.player.Iv(),a.player.Oa("onLiveMediaEnded",b)));return e},YWa=function(a){var b=0;
a&&a.pollDelayMs&&(a=Number(a.pollDelayMs))&&(b=a);return b},R3=function(a,b,c){var d=a.player.V();
if(!a.u.isActive()){a.u.stop();a.S++;var e=b?"heartbeat.net":"heartbeat.servererror";var f=a.getVideoData();if(f.bK||b&&!g.kE(a.getVideoData())&&!P3(a)&&f.isLivePlayback)f=!1;else{var k,l;(null==(l=a.heartbeatParams)?0:l.Dv)?k=a.heartbeatParams.Dv:k=f.aK||5;f=a.S>=k}f?(g.Ds("heartbeatActionPlayerHalted",b?{enforcedPolicyToHaltOnNetworkFailure:!0}:XWa()),(b=a.getVideoData())&&b.isLivePlayback?a.player.rg(e,1,"Video playback interrupted. Please try again.",c):a.player.rg(e,1,"Sorry, there was an error licensing this video.",
c)):(d.N("html5_report_non_fatal_heartbeat_error")&&a.player.qo(e,{msg:c}),Q3(a,a.J.getValue()),g.Ui(a.J))}},XWa=function(a){var b={enforcedPolicyToHaltOnNetworkFailure:!1};
a&&(b.serializedServerContext=a.additionalLoggingData);return b},S3=function(a){a.S=0;
a.u.stop();a.D=!1;a.sequenceNumber=0},OWa=function(a){var b=a.getVideoData(),c=a.player.V();
if(b.isLivePlayback)if(g.zB(c.u)){a.C=!0;a.K=!0;if(!g.IC(c)||g.TC(c))a.offlineSlate=new K3(a.player),g.H(a,a.offlineSlate),g.EJ(a.player,a.offlineSlate.element,4);(b=b.getPlayerResponse())&&b.playabilityStatus&&(a.j=b.playabilityStatus);var d;if("UNPLAYABLE"!==(null==(d=a.j)?void 0:d.status)||a.player.N("stop_heartbeat_on_unplayable_live_videos_killswitch"))a.j?(d=YWa(a.j.liveStreamability&&a.j.liveStreamability.liveStreamabilityRenderer))?Q3(a,d):Q3(a,7500):Q3(a,1E3)}else a.player.rg("html5.unsupportedlive",
2,"HTML5_NO_AVAILABLE_FORMATS_FALLBACK","nolive.1");else!c.N("html5_release_post_live_heartbeat_killswitch")&&g.Sb(b.ra,"heartbeat")&&a.player.mf("heartbeat",a.getPlayerType())},WWa=function(a){return(a=a.player.getProgressState(a.getPlayerType()).ingestionTime)&&isFinite(a)?""+Math.floor(1E3*a):null},SWa=function(a){try{var b=JSON.parse(a);
return null!=b?b:void 0}catch(c){}},RWa=["ATTESTATION_ERROR_UNKNOWN",
"ATTESTATION_ERROR_VM_NOT_INITIALIZED","ATTESTATION_ERROR_VM_NO_RESPONSE","ATTESTATION_ERROR_VM_TIMEOUT","ATTESTATION_ERROR_VM_INTERNAL_ERROR"],ZWa={ERAS:["BC","AD"],ERANAMES:["Before Christ","Anno Domini"],NARROWMONTHS:"JFMAMJJASOND".split(""),STANDALONENARROWMONTHS:"JFMAMJJASOND".split(""),MONTHS:"January February March April May June July August September October November December".split(" "),STANDALONEMONTHS:"January February March April May June July August September October November December".split(" "),
SHORTMONTHS:"Jan Feb Mar Apr May Jun Jul Aug Sep Oct Nov Dec".split(" "),STANDALONESHORTMONTHS:"Jan Feb Mar Apr May Jun Jul Aug Sep Oct Nov Dec".split(" "),WEEKDAYS:"Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),STANDALONEWEEKDAYS:"Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),SHORTWEEKDAYS:"Sun Mon Tue Wed Thu Fri Sat".split(" "),STANDALONESHORTWEEKDAYS:"Sun Mon Tue Wed Thu Fri Sat".split(" "),NARROWWEEKDAYS:"SMTWTFS".split(""),STANDALONENARROWWEEKDAYS:"SMTWTFS".split(""),
SHORTQUARTERS:["Q1","Q2","Q3","Q4"],QUARTERS:["1st quarter","2nd quarter","3rd quarter","4th quarter"],AMPMS:["AM","PM"],DATEFORMATS:["EEEE, MMMM d, y","MMMM d, y","MMM d, y","M/d/yy"],TIMEFORMATS:["h:mm:ss a zzzz","h:mm:ss a z","h:mm:ss a","h:mm a"],DATETIMEFORMATS:["{1} 'at' {0}","{1} 'at' {0}","{1}, {0}","{1}, {0}"],FIRSTDAYOFWEEK:6,WEEKENDRANGE:[5,6],FIRSTWEEKCUTOFFDAY:5},T3=ZWa;T3=ZWa;g.h=F3.prototype;g.h.jN=T3.FIRSTDAYOFWEEK;g.h.kN=T3.FIRSTWEEKCUTOFFDAY;g.h.clone=function(){var a=new F3(this.date);a.jN=this.jN;a.kN=this.kN;return a};
g.h.getFullYear=function(){return this.date.getFullYear()};
g.h.getMonth=function(){return this.date.getMonth()};
g.h.getDate=function(){return this.date.getDate()};
g.h.set=function(a){this.date=new Date(a.getFullYear(),a.getMonth(),a.getDate())};
g.h.add=function(a){if(a.u||a.j){var b=this.getMonth()+a.j+12*a.u,c=this.getFullYear()+Math.floor(b/12);b%=12;0>b&&(b+=12);a:{switch(b){case 1:var d=0!=c%4||0==c%100&&0!=c%400?28:29;break a;case 5:case 8:case 10:case 3:d=30;break a}d=31}d=Math.min(d,this.getDate());this.date.setDate(1);this.date.setFullYear(c);this.date.setMonth(b);this.date.setDate(d)}a.days&&(c=this.getFullYear(),b=0<=c&&99>=c?-1900:0,a=new Date((new Date(c,this.getMonth(),this.getDate(),12)).getTime()+864E5*a.days),this.date.setDate(1),
this.date.setFullYear(a.getFullYear()+b),this.date.setMonth(a.getMonth()),this.date.setDate(a.getDate()),E3(this,a.getDate()))};
g.h.equals=function(a){return!(!a||this.getFullYear()!=a.getFullYear()||this.getMonth()!=a.getMonth()||this.getDate()!=a.getDate())};
g.h.toString=function(){var a=this.getFullYear(),b=0>a?"-":1E4<=a?"+":"";return[b+D3(Math.abs(a),b?6:4),D3(this.getMonth()+1,2),D3(this.getDate(),2)].join("")+""};
g.h.valueOf=function(){return this.date.valueOf()};g.w(G3,g.OK);G3.prototype.hide=function(){this.buttonElement&&this.buttonElement.removeAttribute("aria-haspopup");g.OK.prototype.hide.call(this)};
G3.prototype.show=function(){this.buttonElement&&this.buttonElement.setAttribute("aria-haspopup","true");g.OK.prototype.show.call(this)};
G3.prototype.qa=function(){g.of(this.j);g.OK.prototype.qa.call(this)};g.w(H3,g.V);
H3.prototype.D=function(){if(this.toggleButtonRenderer){var a=this.toggleButtonRenderer;a.isToggled?this.B(a.toggledServiceEndpoint):this.B(a.defaultServiceEndpoint);a.isToggled=!a.isToggled;I3(this)}else if(this.upcomingEventReminderButtonRenderer)if(this.j&&this.j.sb)this.j.Gb();else{var b=HWa(this);b&&this.B(b.serviceEndpoint||b.command);b=g.r(b&&b.command&&b.command.commandExecutorCommand&&b.command.commandExecutorCommand.commands||[]);for(var c=b.next();!c.done;c=b.next())if((c=c.value)&&c.openPopupAction&&
c.openPopupAction.popup&&c.openPopupAction.popup.menuPopupRenderer){a=c.openPopupAction.popup.menuPopupRenderer;break}this.j||(this.j=new G3(this.I,this.buttonElement),this.j.Ba(this.element),g.H(this,this.j),this.j.subscribe("reminderMenuItemClicked",this.B,this));b=this.j;b.menuPopupRenderer=a;FWa(b)}};
H3.prototype.B=function(a){if(a&&(a.addUpcomingEventReminderEndpoint||a.removeUpcomingEventReminderEndpoint)){if(a.addUpcomingEventReminderEndpoint){var b=a.addUpcomingEventReminderEndpoint;var c="notification/add_upcoming_event_reminder"}else a.removeUpcomingEventReminderEndpoint&&(b=a.removeUpcomingEventReminderEndpoint,c="notification/remove_upcoming_event_reminder");if(c&&b&&b.params)for(JWa(this,c,b.params),a=g.r(b.commands||[]),b=a.next();!b.done;b=a.next())if((b=b.value)&&b.updateUpcomingEventReminderButtonStateCommand){this.u=
b.updateUpcomingEventReminderButtonStateCommand.state;I3(this);break}}};g.w(K3,g.V);g.h=K3.prototype;g.h.getPlayerType=function(){if(8===this.api.getPresentingPlayerType())return 1};
g.h.getVideoData=function(){return this.api.getVideoData(this.getPlayerType())};
g.h.Ha=function(a){var b,c,d=null==a?void 0:null==(b=a.liveStreamability)?void 0:null==(c=b.liveStreamabilityRenderer)?void 0:c.offlineSlate;if(d){this.u=a;b=d.liveStreamOfflineSlateRenderer;b.canShowCountdown?this.HR():L3(this,b);var e,f,k,l;if(c=null==a?void 0:null==(e=a.liveStreamability)?void 0:null==(f=e.liveStreamabilityRenderer)?void 0:null==(k=f.offlineSlate)?void 0:null==(l=k.liveStreamOfflineSlateRenderer)?void 0:l.thumbnail){e=0;f=null;k=c.thumbnails;for(l=0;l<k.length;l++)k[l].width>e&&
(e=k[l].width||0,f=k[l].url);f&&(this.background.style.backgroundImage="url("+f+")")}else this.background.style.backgroundImage="";b.actionButtons||b.reminderButton?(this.j||(this.j=new H3(this.api),this.j.Ba(this.Ca("ytp-offline-slate-buttons")),g.H(this,this.j)),GWa(this.j,b.actionButtons&&b.actionButtons[0],b.reminderButton)):this.j&&GWa(this.j,null,null);this.u=a}else this.u=null;this.KR()};
g.h.KR=function(a){if(8===this.api.getPresentingPlayerType())var b=!0;else{var c=this.api.yb(),d=this.getVideoData();b=d.isLivePlayback&&(g.iG(c)||g.U(c,2)||g.U(c,64));var e=2===d.autonavState&&g.U(c,2);c=c.Nc()&&!g.pE(d)&&!this.api.isAtLiveHead(void 0,!0);b=b&&!c&&!e}b&&this.u?this.sb?(null==a?0:g.yF(a,2))&&!this.getVideoData().Wj&&(g.Hp(this.element,"ytp-offline-slate-collapsed"),this.C.stop(),g.Hp(this.B,"ytp-offline-slate-bar-fade"),this.D.start()):(this.show(),this.C.start(),this.api.ea("offlineslatestatechange"),
this.J&&this.api.Iv()):this.sb&&(this.hide(),this.api.ea("offlineslatestatechange"))};
g.h.HR=function(){var a,b,c,d,e=null==(a=this.u)?void 0:null==(b=a.liveStreamability)?void 0:null==(c=b.liveStreamabilityRenderer)?void 0:null==(d=c.offlineSlate)?void 0:d.liveStreamOfflineSlateRenderer;e&&(a=Math.floor(g.Ta()/1E3),b=e.canShowCountdown&&Number(e.scheduledStartTime),!b||b<=a?(L3(this,e),this.countdownTimer.stop()):(L3(this,e,g.XH(b-a)),g.zp(this.countdownTimer)))};
g.h.qa=function(){this.countdownTimer.dispose();this.countdownTimer=null;g.V.prototype.qa.call(this)};M3.prototype.u=function(a){return this.trigger&&a.trigger?this.trigger===a.trigger&&this.j===a.j:!1};
M3.prototype.isExpired=function(){return 6E4<(0,g.R)()-this.B};
M3.prototype.toString=function(){return"heartbeat:"+this.trigger+":"+this.j};g.w(O3,g.cK);g.h=O3.prototype;g.h.qa=function(){S3(this);this.player.Nf("heartbeat");g.cK.prototype.qa.call(this)};
g.h.onCueRangeEnter=function(){this.K=!0;Q3(this,2E3)};
g.h.Qy=function(a){this.heartbeatParams=a;Q3(this,2E3)};
g.h.dU=function(a){var b;8===this.player.getPresentingPlayerType()||"UNPLAYABLE"===(null==(b=this.j)?void 0:b.status)&&!this.player.N("stop_heartbeat_on_unplayable_live_videos_killswitch")||(g.U(a.state,2)||g.U(a.state,64)?(S3(this),this.C&&(this.K=!0,Q3(this,1E3))):(g.U(a.state,1)||g.U(a.state,8))&&Q3(this,2E3))};
g.h.eU=function(){3!==this.player.getPresentingPlayerType()&&Q3(this,2E3)};
g.h.getPlayerType=function(){if(8===this.player.getPresentingPlayerType())return 1};
g.h.getVideoData=function(){return this.player.getVideoData(this.getPlayerType())};
g.h.aj=function(a){switch(a){case 4:case 3:return!1}return!0};
g.h.aC=function(a,b,c){a={trigger:a,reason:b};c&&(a.serializedServerContext=c.additionalLoggingData);g.Ds("heartbeatActionPlayerTransitioned",a)};
g.h.jf=function(a){var b="LICENSE",c=SWa(a);if(c)return c.reason||g.IK[b]||"";(a=a.match(TWa))&&(a=Number(a[1]))&&(b=g.nxa(a));return g.IK[b]||""};
g.h.py=function(){return!!this.offlineSlate&&this.offlineSlate.sb};
var TWa=/^GLS\/1.0 (\d+) (\w+).*?\r\n\r\n([\S\s]*)$/;g.bK("heartbeat",O3);})(_yt_player);
